# LOSS OR COST FUNCTIONS

In [52]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [53]:
actual= np.array([1,1,0,0,1])
predicted= np.array([0.30,0.7,1,0,0.5])

Implementation of MEAN ABSOLUTE ERROR

In [54]:
def mae(actual, predicted):
    total_error = 0
    for yp, yt in zip(actual, predicted):
        total_error += abs(yp - yt)
    print("Total error is:",total_error)
    mae = total_error/len(actual)
    print("Mean absolute error is:",mae)
    return mae

In [55]:
mae(actual,predicted)

Total error is: 2.5
Mean absolute error is: 0.5


0.5

Using Numpy

In [56]:
np.abs(actual-predicted)

array([0.7, 0.3, 1. , 0. , 0.5])

In [57]:
np.mean(np.abs(actual-predicted))

0.5

In [58]:
def mae_np(actual, predicted):
    return np.mean(np.abs(actual-predicted))

In [59]:
mae_np(actual,predicted)

0.5

#Implement Log Loss or Binary Cross Entropy

In [60]:
np.log([0])

C:\Users\user\AppData\Local\Temp/ipykernel_2896/262464415.py:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [61]:
epsilon = 1e-15

In [62]:
np.log([1e-15])

array([-34.53877639])

In [63]:
actual

array([1, 1, 0, 0, 1])

In [64]:
y_predicted_new = [max(i,epsilon) for i in actual]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [65]:
1-epsilon

0.999999999999999

In [66]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [67]:
y_predicted_new = np.array(y_predicted_new)

In [68]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [70]:
-np.mean(predicted*np.log(y_predicted_new)+(1-predicted)*np.log(1-y_predicted_new))

17.2696280766844

Using Python

In [71]:
def log_loss(predicted,actual):
    y_predicted_new = [max(i,epsilon) for i in actual]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(predicted*np.log(y_predicted_new)+(1-predicted)*np.log(1-y_predicted_new))

In [72]:
log_loss(predicted, actual)

17.2696280766844

Implementation of MSE

In [73]:
def mse(actual, predicted):
    total_error = 0
    for yt, yp in zip(predicted, actual):
        total_error += (yt-yp)**2
    print("Total Squared Error:",total_error)
    mse = total_error/len(predicted)
    print("Mean Squared Error:",mse)
    return mse

In [74]:
mse(predicted, actual)

Total Squared Error: 1.83
Mean Squared Error: 0.366


0.366

With Numpy 

In [76]:
np.mean(np.square(predicted-actual))

0.366